import express, { type Express, type Request, type Response, type NextFunction } from "express";
import fs from "fs";
import { type Server } from "http";
import { nanoid } from "nanoid";
import path from "path";
import { createServer as createViteServer } from "vite";
import viteConfig from "../../vite.config";
import { seoPrerender } from "../seoPrerender";

export async function setupVite(app: Express, server: Server) {
  const serverOptions = {
    middlewareMode: true,
    hmr: { server },
    allowedHosts: true as const,
  };

  const vite = await createViteServer({
    ...viteConfig,
    configFile: false,
    server: serverOptions,
    appType: "custom",
  });

  // SEO prerender MUST run before vite.middlewares to intercept bot requests
  app.use(async (req: Request, res: Response, next: NextFunction) => {
    const prerenderResult = await seoPrerender(req);
    if (prerenderResult) {
      res.setHeader("X-Prerender", "true");
      res.setHeader("Cache-Control", "public, max-age=3600");
      // Vary: User-Agent tells Google that bots and browsers get different content
      res.setHeader("Vary", "User-Agent");
      return res.status(200).set({ "Content-Type": "text/html; charset=utf-8" }).end(prerenderResult);
    }
    next();
  });

  app.use(vite.middlewares);
  app.use("*", async (req: Request, res: Response, next: NextFunction) => {

    const url = req.originalUrl;

    try {
      const clientTemplate = path.resolve(
        import.meta.dirname,
        "../..",
        "client",
        "index.html"
      );

      // always reload the index.html file from disk incase it changes
      let template = await fs.promises.readFile(clientTemplate, "utf-8");
      template = template.replace(
        `src="/src/main.tsx"`,
        `src="/src/main.tsx?v=${nanoid()}"`
      );
      const page = await vite.transformIndexHtml(url, template);
      res.status(200).set({ "Content-Type": "text/html" }).end(page);
    } catch (e) {
      vite.ssrFixStacktrace(e as Error);
      next(e);
    }
  });
}

export function serveStatic(app: Express) {
  const distPath =
    process.env.NODE_ENV === "development"
      ? path.resolve(import.meta.dirname, "../..", "dist", "public")
      : path.resolve(import.meta.dirname, "public");
  if (!fs.existsSync(distPath)) {
    console.error(
      `Could not find the build directory: ${distPath}, make sure to build the client first`
    );
  }

  // Serve pre-compressed .br and .gz files generated by vite-plugin-compression2
  // This avoids on-the-fly compression and reduces CPU usage significantly
  app.use("/assets", (req: Request, res: Response, next: NextFunction) => {
    const acceptEncoding = req.headers["accept-encoding"] ?? "";
    const filePath = path.join(distPath, "assets", req.path);

    if (typeof acceptEncoding === "string" && acceptEncoding.includes("br")) {
      const brPath = filePath + ".br";
      if (fs.existsSync(brPath)) {
        res.set("Content-Encoding", "br");
        res.set("Cache-Control", "public, max-age=31536000, immutable");
        // Set correct content type based on original extension
        const ext = path.extname(req.path);
        if (ext === ".js") res.set("Content-Type", "application/javascript");
        else if (ext === ".css") res.set("Content-Type", "text/css");
        res.sendFile(brPath);
        return;
      }
    }
    if (typeof acceptEncoding === "string" && acceptEncoding.includes("gzip")) {
      const gzPath = filePath + ".gz";
      if (fs.existsSync(gzPath)) {
        res.set("Content-Encoding", "gzip");
        res.set("Cache-Control", "public, max-age=31536000, immutable");
        const ext = path.extname(req.path);
        if (ext === ".js") res.set("Content-Type", "application/javascript");
        else if (ext === ".css") res.set("Content-Type", "text/css");
        res.sendFile(gzPath);
        return;
      }
    }
    next();
  });

  // Cache hashed assets for 1 year (safe because filenames contain content hash)
  app.use("/assets", express.static(path.join(distPath, "assets"), {
    maxAge: "1y",
    immutable: true,
    etag: false,
    lastModified: false,
  }));

  // Cache other static files (favicon, robots.txt) for 1 day
  app.use(express.static(distPath, {
    maxAge: "1d",
    etag: true,
  }));

  // SPA fallback: serve index.html for all non-file routes
  // Known 404 paths and unknown routes return proper 404 HTTP status
  const KNOWN_VALID_PATHS = new Set([
    "/", "/catalog", "/bestsellers", "/sales", "/premium",
    "/videos", "/sellers", "/about", "/cart", "/checkout",
    "/search", "/login", "/favorites", "/profile",
    "/seller", "/seller/register", "/seller/dashboard", "/seller/messages",
    "/admin", "/admin/analytics", "/admin/reviews", "/404",
  ]);
  const VALID_PATH_PREFIXES = [
    "/category/", "/kategoriya/", "/product/", "/mahsulot/", "/seller/",
  ];

  function isValidSpaPath(reqPath: string): boolean {
    if (KNOWN_VALID_PATHS.has(reqPath)) return true;
    return VALID_PATH_PREFIXES.some(prefix => reqPath.startsWith(prefix));
  }

  app.use("*", async (req: Request, res: Response) => {
    // SEO prerender for production bots
    const prerenderResult = await seoPrerender(req);
    if (prerenderResult) {
      res.setHeader("X-Prerender", "true");
      res.setHeader("Cache-Control", "public, max-age=3600");
      // Vary: User-Agent tells Google that bots and browsers get different content
      res.setHeader("Vary", "User-Agent");
      return res.status(200).set({ "Content-Type": "text/html; charset=utf-8" }).end(prerenderResult);
    }

    const reqPath = req.path;
    // Return 404 for /404 page and unknown routes (fixes Google Search Console false-404 issues)
    const status = isValidSpaPath(reqPath) ? 200 : 404;
    res.status(status).sendFile(path.resolve(distPath, "index.html"));
  });
}
